logging:
  level:
    root: INFO
    # 在日志中输SQL参数的绑定信息
    'org.hibernate.type.descriptor.sql.BasicBinder': TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oli_crm?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: mysqlpwd.umop # 123456
    hikari:
      maximum-pool-size: 10
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
        jdbc:
          batch_size: 500
        order_updates: true
        order_inserts: true
        generate_statistics: false
        hbm2ddl.auto: update

jasypt:
  encryptor:
    # 生产环境通过cli方式传入 -Djasypt.encryptor.password=password
    password: olicrm
    algorithm: "PBEWITHHMACSHA512ANDAES_256"
    salt-generator-classname: "org.jasypt.salt.RandomSaltGenerator"
    iv-generator-classname: "org.jasypt.iv.RandomIvGenerator"
    provider-name: "SunJCE"
    string-output-type: "base64"
    pool-size: 1
    key-obtention-iterations: 1000
