logging:
  level:
    root: INFO
    # 在日志中输SQL参数的绑定信息
    'org.hibernate.type.descriptor.sql.BasicBinder': TRACE

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/umop/umop-db
    username: umop
    password: ENC(HR6HHZUS7DiducOuwj3Gz3HijWyop+pZZazwIQJW9CGPJCEAsObHgNIRhUZ477K2) # h2pwd.umop
  jpa:
    database: h2
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true
        web-admin-password: h2uipwd.umop

jasypt:
  encryptor:
    # 生产环境通过cli方式传入 -Djasypt.encryptor.password=password
    password: Hongshi.umop
    algorithm: "PBEWITHHMACSHA512ANDAES_256"
    salt-generator-classname: "org.jasypt.salt.RandomSaltGenerator"
    iv-generator-classname: "org.jasypt.iv.RandomIvGenerator"
    provider-name: "SunJCE"
    string-output-type: "base64"
    pool-size: 1
    key-obtention-iterations: 1000
