export const SUPERADMIN = {
  SUPERADMIN: 'superadmin',
};

export const USER_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
};

export const CONFIG_BACKUP_DEVICE_SOURCE = {
  LOCAL: 'LOCAL',
  MONITOR: 'MONITOR',
};

export const CONFIG_BACKUP_DEVICE_CERIFICATETYPE = {
  GLOBAL: 'GLOBAL',
  CUSTOM: 'CUSTOM',
};

export const CONFIG_BACKUP_DEVICE_CONNECT_TYPE = {
  SSH: 'SSH',
  TELNET: 'TELNET',
};

export const MONITOR_OBJECT_BATCH_CREATE_SUMMARY_STATUS = {
  DATA_CHECKING: 'DATA_CHECKING',
  DATA_CHECKING_FINISHED: 'DATA_CHECKING_FINISHED',
  MONITORING: 'MONITORING',
  MONITOR_FINISHED: 'MONITOR_FINISHED',
};

export const MONITOR_OBJECT_BATCH_CREATE_DETAIL_STATUS = {
  QUEUE: 'QUEUE',
  VALIDATE_FAILED: 'VALIDATE_FAILED',
  CONNECTIVITY_FAILED: 'CONNECTIVITY_FAILED',
  TEMPLATE_MATCH_ERROR: 'TEMPLATE_MATCH_ERROR',
  WAIT_FOR_MONITOR: 'WAIT_FOR_MONITOR',
  MONITOR_ERROR: 'MONITOR_ERROR',
  MONITOR_SUCCESS: 'MONITOR_SUCCESS',
};

export const NETWORK_MONITOR_OBJECT_BATCH_UPDATE_DETAIL_STATUS = {
  QUEUE: 'QUEUE',
  UPDATE_ERROR: 'UPDATE_ERROR',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS',
};

export const NETWORK_MONITOR_OBJECT_BATCH_UPDATE_DETAIL_STATUS_MAPPING = {
  QUEUE: '排队中',
  SNMP_TESTING: 'snmp连通性测试中',
  UPDATE_ERROR: '更新失败',
  UPDATE_SUCCESS: '更新成功',
};

export const COMMON_ROLE_USER_IGNORE_MENU_NAMES = [];

export const SUPERADMIN_ROLE_ID = '2';

export const AGENT_DIST = 'agent-install';
export const HELP_CENTER_ATTACH_TYPE = 'help-center';

/**
 * 是否是网络设备类表单
 * 网络设备,存储,安全设备,服务器 目前使用snmp方式进行监控,表单样式统一为网络设备类表单
 */
export const NETWORK_DEVICE_LIKE_CATEGORY = [
  'network_device',
  'storage',
  'secure',
  'server',
];
